use_frameworks!

platform :ios, '13.0'

target 'Moisture_Example' do

#  pod 'Moisture', :path => '../'
#  
  pod 'Moisture/Rx', :path => '../'
  
  target 'Moisture_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
